"""Initial migration

Revision ID: ff06474208a7
Revises: 
Create Date: 2024-11-11 18:01:51.018828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff06474208a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('prediction_result', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('exercise_done', sa.Boolean(), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=True),
    sa.Column('took_medication', sa.Boolean(), nullable=False),
    sa.Column('diet_notes', sa.String(length=500), nullable=True),
    sa.Column('additional_notes', sa.String(length=500), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('analysis_summary', sa.String(length=1000), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_analysis')
    op.drop_table('symptom_logs')
    op.drop_table('predictions')
    op.drop_table('users')
    # ### end Alembic commands ###
